# AWS SITL Inventory
# Updated by Terraform — 2026-03-24
# Key: infra/terraform/sitl-key.pem

all:
  children:
    sim_host:
      hosts:
        sitl-aws:
          ansible_host: "13.234.232.144"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /Users/ashidudissanayake/Dev/drone-platform/infra/terraform/sitl-key.pem
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=30'
